apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
  - external-secrets/secretstore.yaml
  - external-secrets/externalsecrets.yaml
  - bootstrap/sql-configmap.yaml
  - bootstrap/db-migrate-job.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: togglemaster
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
